version: 0.0
os: linux


files:
  - source: / # 인스턴스에 복사할 디렉토리 경로
    destination: /home/ubuntu/xolar # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes # 인스턴스에서 현재 배포중인 애플리케이션 파일이 인스턴스에 이미 있는 버전을 대체
file_exists_behavior: OVERWRITE

# 'files' 섹션의 파일 및 디렉토리가 인스턴스에 복사된 후 권한을 지정받는 방법
permissions:
  - object: / # 권한이 지정되는 파일 또는 디렉토리
    pattern: "**" # (선택사항) 매칭되는 패턴에만 권한 부여
    owner: ubuntu # (선택사항) object 소유자
    group: ubuntu # (선택사항) object의 그룹 이름

# 배포 과정 중 특정 이벤트에서 실행되는 스크립트 지정
hooks:
  AfterInstall:
    - location: scripts/stop.sh # 스크립트 파일 위치
      timeout: 60 # (선택사항) 스크립트 실행 실패를 판단하는 제한 시간
      runas: ubuntu # (선택사항) 스크립트를 실행하는 사용자
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
